### ISSUE TITLE
Contradictory description in the doc of Shubbery Notation

### ISSUE THREAD

**Issue by s-cerevisiae** [racket/rhombus-prototype#244]
In the prototype documentation of the Shubbery Notation, [Section 2.3](https://plt.cs.northwestern.edu/pkg-build/doc/shrubbery/group-and-block.html#%28part._.Blocking_with___and_.Indentation%29) says that
> Subsequent groups in a sequence must start with the same indentation as the first group.
> ```
> group 1
> group 2
> // error, because the group is indented incorrectly:
>   group 3
> ```
I took the word *error* as it would be illegal to indent like that.

But in the immediately following section ([Section 2.4](https://plt.cs.northwestern.edu/pkg-build/doc/shrubbery/group-and-block.html#%28part._continuing-op%29)), it says
> The following two groups are the same:
> ```
> f(1) + 2
>   + 3 + 4
>   - 5 - 6
>
> f(1) + 2 + 3 + 4 - 5 - 6
> ```
Which, in my opinion, means that this is legal, and will only make the lines a whole group.

I'm not a native speaker, so I'd like to know if it's only me or the wording is being a bit misleading.

**Comment by s-cerevisiae** [comment]
Closing this because I found it is unhelpful and probably bikeshedding, which is not needed during this early stage of the project.

**Comment by sorawee** [comment]
I don't think there's anything incorrect.

```
1 + 2
  + 1 + 2

// parsed as '(top (group 1 (op +) 2 (op +) 1 (op +) 2))
```

has only one group. The operator at the beginning indicates a continuation of the group in the next line.

In contrast, this has two different groups:

```
1 + 2
1 + 2

// parsed as '(top (group 1 (op +) 2) (group 1 (op +) 2))
```

And indeed, if we indent correctly, it errors:

```
1 + 2
  1 + 2

// wrong indentation (or missing `:` on previous line)
```

**Comment by s-cerevisiae** [comment]
> And indeed, if we indent correctly, it errors:
> 
> ```
> 1 + 2
>   1 + 2
> 
> // wrong indentation (or missing `:` on previous line)
> ```

Oh I see. My mind must have been absent when filing the issue....
