### ISSUE TITLE
Variable and array assignments evaluate inconsistently

### ISSUE THREAD

**Issue by jackfirth** [racket/rhombus-prototype#253]
In this code:

```
#lang rhombus
val mutable xs: Array(1, 2, 3)
xs[1] := 100
xs := 100
```

The `xs[1] := 100` expression evaluates to `#void`, but the `xs := 100` expression evaluates to `100`. This seems inconsistent. I'd prefer they both evaluate to `#void`, so I don't have to sprinkle `#void` at the end of state-changing methods on mutable classes that happen to update fields.

**Comment by jackfirth** [comment]
Field assignments appear to still return their right-hand sides. In this program:

```
#lang rhombus

class Foo():
  private field x: 0
  method test(): x := 2

let mutable x: 0
x := 1

Foo().test()
```
...the `x := 1` expression evaluates to `#void` as expected, but the `Foo().test()` expression evaluates to `2` instead of `#void`.

**Comment by mflatt** [comment]
Looks like I missed at least one case.
