### ISSUE TITLE
Nested fields can't be mutated

### ISSUE THREAD

**Issue by jackfirth** [racket/rhombus-prototype#256]
This code:

```
class Outer():
  field child = Inner()

class Inner():
  field x = 4

let parent = Outer()
parent.child.x := 5
```

...fails to compile with `:=: left-hand argument is not a mutable identifier in: :=`

**Comment by jackfirth** [comment]
This also fails to compile:

```
class Foo():
  field bars = Array(Bar(), Bar(), Bar())

class Bar():
  field x = 1

let foo = Foo()
foo.bars[1].x := 2
```

**Comment by jackfirth** [comment]
The soup thickens. If I add annotations, the singular case works:

```
class Inner():
  field x = 4

class Outer():
  field child :: Inner = Inner()

let parent = Outer()
parent.child.x := 5
```

...but the array case doesn't work:

```
class Bar():
  field x = 1

class Foo():
  field bars :: Array.of(Bar) = Array(Bar(), Bar(), Bar())

let foo = Foo()
foo.bars[1].x := 2
```

**Comment by mflatt** [comment]
You do need to include annotations, but `Array.of` doesn't propagate static information correctly, and I'll push a repair.

**Comment by mflatt** [comment]
(Leaving the PR open the "`:=` requires static information?" part, because it does seem like `.` plus `:=` should support dynamic mode.)
