### ISSUE TITLE
Inconsistent class and interface override syntax

### ISSUE THREAD

**Issue by jackfirth** [racket/rhombus-prototype#261]
This code compiles:

```
class Foo():
  nonfinal
  method foo() :: Foo:
    this

class Bar():
  extends Foo
  override method foo() :: Bar:
    this
 ```

But this code doesn't compile:

```
interface Foo:
  method foo() :: Foo

interface Bar:
  extends Foo
  override method foo() :: Bar
```

It fails with this error:

```
override: expected more terms
  parsing context: 
   while parsing different things...
   while parsing method implementation in: override method foo() :: Bar
```

Is one supposed to use `override method foo()` or `override foo()` to override members in a class or interface? Classes allow both, but interfaces seem to only allow the latter.

Given that a class's overridable members are all in the same namespace, I prefer `override foo()` as the required form. I think `override method foo()` / `override property foo` shouldn't be allowed.

**Comment by mflatt** [comment]
This is supposed to work, but `override` is apparently not set up for an implicit `abstract` when there's no implementation. So, you can work around this for the moment by using `abstract override`. (The "more terms" expected currently is the implementation of the method.)
