### ISSUE TITLE
Subinterfaces can't override properties

### ISSUE THREAD

**Issue by jackfirth** [racket/rhombus-prototype#262]
This code:

```
interface Foo:
  property foo :: Foo

interface Bar:
  extends Foo
  override foo :: Bar
```

...fails to compile with `interface: cannot override interface's property with a non-property method in: foo`. But if properties are intended to work semantically like methods that are implicitly called, then subinterfaces should be able to override them too.

My use case for this is a `MapView.keys :: SetView` property that the `Map` and `MutableMap` interfaces want to refine to `keys :: Set` and `keys :: MutableSet`, respectively.

**Comment by mflatt** [comment]
You would need to use `override property`, but I bet you tried that and got an error, for the same reason as with methods. So, `abstract override property` should do what you want at the moment.

**Comment by mflatt** [comment]
This bug is fixed, assuming that `override property` is what you meant to write in the example.
