### ISSUE TITLE
Reserved words in Python

### ISSUE THREAD

**Issue by gus-massa** [racket/rhombus-prototype#309]
An slightly off-topic rant, but this bit me a few days ago

```
#lang python
def add7(A):
  m, n = A.shape
  for im in range(m):
    for in in range(n):
      A[im, in] += 7
```

I had too many indexes in my calculation, so my brilliant idea was to use `m` as the size and `im` as the index, but it´s a problem with `n` and `in`.

I'm too used to reuse arbitrary names in Racket. How bad is this problem in Rhombus? 

PS: I know about broadcasting, this is just a very simplified version. Also, broadcasting is surprisingly faster.

**Comment by mflatt** [comment]
Rhombus is like Racket: there are no reserved words.

**Comment by rfindler** [comment]
I guess in Rhombus the keyword in would be `~in` so it's not a problem, but if `in` were shadowed here (like `else` in a `cond`) that would actually be a worse outcome?

**Comment by gus-massa** [comment]
I'm never sure, so I just tired redefining `=>` and `else` before a `cond` and it detects the change (as expected).

```
#lang racket
(define x 7)
(let ([else #f])
  (cond
    [(string? x) 'yes]
    [else 'no]))     ; ==> invisible #<void>
```

I never has to do this in a real program, but it's nice that it's possible just in case.
