### ISSUE TITLE
Is there any way to get the head syntax object？

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/rhombus-prototype#317]
The head syntax object is useful when writing unhygienic macros, otherwise, I can only find outside scopes from anywhere else.
It seems impossible to get the head syntax object now.

**Comment by mflatt** [comment]
You can declare `~op_stx` to get the head term:

```
#lang rhombus/and_meta

namespace ns:
  export hello
  expr.macro 'hello':
    ~op_stx self
    println("called as " +& self)
    '#void'

import .ns.hello as howdy

howdy
```

prints "called as howdy"

**Comment by Syntacticlosure** [comment]
thank u.
