### ISSUE TITLE
RFC: Improving Syntax.replace_scopes

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/rhombus-prototype#318]
Intuitively, one may think id and '$id' have the same behavior if it is just an identifier because in racket they do.

In rhombus, the statement is true in most cases, however, it is not true in the case of `Syntax.replace_scopes`.

The following two pieces of codes are almost identical, but get different results:
```rhombus
import rhombus/meta open
expr.macro 'test: $expr':
  ~op_stx h
  def y: 'y'.replace_scopes(h)
  'block:
     def $y: 2
     $expr'

test: y
```

```rhombus
import rhombus/meta open
expr.macro 'test: $expr':
  ~op_stx h
  def y: 'y'.replace_scopes('$h')
  'block:
     def $y: 2
     $expr'
```
This is because '$y' is not an actual identifier but `(group y)` packed by the function `unpack-group`.

If we extract the identifier inside the `group` structure, we can get the correct result:
```rhombus
import rhombus/meta open
expr.macro 'test: $expr':
  ~op_stx h
  def y: 'y'.replace_scopes('$h'.unwrap_group().first)
  'block:
     def $y: 2
     $expr'

test: y
```
-----------------
I noticed that the current implementation of `Syntax.replace_scopes` is just a recursive wrapper of `datum->syntax`. I don't think it is suitable for rhombus because you don't know whether your syntax object is wrapped by some implicit structures that generated by quasiquote.

I propose that we can restrict the context parameter of `Syntax.replace_scopes` to a single term object or an identifier and apply `unpack-term` to it to get the real scopes.

If you like my proposal, I can make a pull request as soon as possible.
```[tasklist]
### Tasks
```

**Comment by mflatt** [comment]
I agree — that sounds like the right repair to `Syntax.replace_scopes`.
