### ISSUE TITLE
How to manipulate `parsed` structure in rhombus?

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/rhombus-prototype#326]
Rhombus provides users the ability to define new DSLs (bindings, annotations, for reducers, etc), or extensible macros in Racket (like match expanders) by `define-enforest`.
However, these facilities rely on parsed structures that encapsulate a s-expression. Anyone who wants to implement their DSLs in Rhombus must write some Racket codes.
Is it acceptable for rhombus users or anyone who doesn't like s-expressions?

**Comment by samdphillips** [comment]
I'm not sure I understand your question.  In the current implementation, it is possible to implement DSLs without dropping into Racket.  See the regular expression dsl Matthew wrote:

[rhombus/tests/rx-space.rhm](https://github.com/racket/rhombus-prototype/blob/master/rhombus/tests/rx-space.rhm)

**Comment by Syntacticlosure** [comment]
I got it.

But, it seems I need to control the enforestation of macro results:
```racket
regexp.macro 'any_alias':
  def '$(x::regexp_meta.Parsed)': 'any'
  x

> rx 'any_alias'
#{'#px"."}
```
I think it is not a big problem.

**Comment by mflatt** [comment]
I agree that a piece is missing here: when you make a new space, you may want facilities analogous to `bind_meta.pack` and `bind_meta.unpack`, and when the result of a macro is not a packed form, then it should be expanded recursively. In other words, it should be possible to support `regexp.macro 'any_alias': 'any'`.

**Comment by mflatt** [comment]
I've pushed an addition to `space.enforest` and an update to the `rx-space.rhm` example to demonstrate.

**Comment by Syntacticlosure** [comment]
This is what I really want.
