### ISSUE TITLE
What is the default `~mode` of `print{,ln}`?

### ISSUE THREAD

**Issue by usaoc** [racket/rhombus-prototype#343]
The documentation of `print{,ln}` says that the default `~mode` is `#'expr`, while [the implementation](https://github.com/racket/rhombus-prototype/blob/5289751d3d020dd4b1a9b03de73c78ae2097b4d5/rhombus/private/print.rkt#L60) uses `#'text`.

**Comment by mflatt** [comment]
The implementation matches the intent, so I'll fix the docs.

Thanks!
