### ISSUE TITLE
Static information in `recur`

### ISSUE THREAD

**Issue by usaoc** [racket/rhombus-prototype#344]
Should the static information of default expression be propagated to each argument in `recur`?  For example, this currently doesn’t work:

```
#lang rhombus/static
recur loop(bx = Box(1)):
  bx.value
```

**Comment by mflatt** [comment]
No, it shouldn't be propagated, since it wouldn't always be right:

```
recur loop(bx = Box(1)):
  if bx
  | loop(#false)
  | bx.value
```

It's the same as arguments for functions with defaults in general.

**Comment by usaoc** [comment]
Ah, I see.  Yes, it occurs clearer to me now—the invariant cannot be maintained without a check.
