### ISSUE TITLE
Clarification for `class.together`

### ISSUE THREAD

**Issue by usaoc** [racket/rhombus-prototype#345]
`class.together` seems to make class/interface names unavailable in `extends`/`implements`.  For example, the below three variants all fail:

```
#lang rhombus/static
class.together:
  class Base():
    nonfinal
  class Extend():
    extends Base
```

```
#lang rhombus/static
class.together:
  interface Base
  interface Extend:
    extends Base
```

```
#lang rhombus/static
class.together:
  interface Interface
  class Class():
    implements Interface
```

The documentation doesn’t make it clear if this is the intended behavior.

**Comment by mflatt** [comment]
`class.together` is not intended to be limited in that way, but I see that I'll need to do more to make subclassing within `class.together` possible.

**Comment by mflatt** [comment]
In commit 476894900dc7dc52ba93ecd44893775bf7ead1d9, the implementation of `class.together` changed to fixed this problem.
