### ISSUE TITLE
Add single quote in 'drracket:quote-matches?

### ISSUE THREAD

**Issue by greghendershott** [racket/rhombus-prototype#353]
Currently rhombus returns `'(#\")`.

Instead should it be `'(#\" #\')`?

(I'd just go ahead and make a PR to add `#\'`, but maybe the omission is intentional? My only thought process is that users of `electric-pairs-mode` in Emacs, and similar stuff in other tools, would probably want both for convenience; whether the quoting is about strings or syntax is N/A in that context?)

**Comment by mflatt** [comment]
A single quote in Rhombus is more like a parenthesis than a double quote. So I think it probably should not be in `drracket:quote-matches?`, but I'm not completely sure.

**Comment by sorawee** [comment]
See also https://github.com/racket/drracket/issues/624. I was not aware of `'drracket:quote-matches` though. It could be that this is already configurable.

**Comment by greghendershott** [comment]
My read of `drracket:paren-matches` and `drracket:quote-matches` is that both let a lang describe various delimiters that are used in pairs.

The "parens" have different open and close. The "quotes" are self-closing.

Regardless, a tool can do automatic pairing (you type the open, you get the close) and with varying degrees of effort/smarts about keeping things balanced.

I read this as "mechanical", with no deeper semantics.

Users conveniently avoid manually configuring a convenient typing/editing feature.

That's a useful thing... but maybe not exactly what you and @rfindler had in mind for these info keys?

**Comment by mflatt** [comment]
I see - thanks!
