### ISSUE TITLE
Dark theme hides commented colons

### ISSUE THREAD

**Issue by sorawee** [racket/rhombus-prototype#434]
I guess it's not a Rhombus problem per se, but the problem is surfaced through Rhombus, so let me report it here.

In default dark themes, commented colons have the same color as the background, making it appear invisible.

<img width="229" alt="Screenshot 2023-12-11 at 9 35 19 PM" src="https://github.com/racket/rhombus-prototype/assets/9099577/d33454c3-c504-405a-abf6-6fb6a95ed088">

<img width="237" alt="Screenshot 2023-12-11 at 9 35 52 PM" src="https://github.com/racket/rhombus-prototype/assets/9099577/dc16f8d1-378d-4a03-bc3a-f78692defe57">

**Comment by rfindler** [comment]
This looks like an interaction between commenting out (which, I think,
draws the colors with an alpha value of .5 or so) and one of the colors in
the color scheme (which are, theoretically, under your control but is,
practically, a problem probably with the defaults).

So I guess the next step would be to figure out which color it is (you can
see the non-alpha-iced colors in the preferences) and see if changing the
default is a good idea or not.

Robby

**Comment by mflatt** [comment]
Repaired by racket/gui@565ce189357f974057a8fad1ea373f95a9346ebf.
