### ISSUE TITLE
identifiers with dots in them

### ISSUE THREAD

**Issue by rfindler** [racket/rhombus-prototype#445]
It seems like something has broken identifiers with dots in them (the original error that tipped me off is [here](https://github.com/rfindler/esterel/actions/runs/7266176667/job/19800370089)).

For example, with this file:
```
#lang rhombus/static/and_meta
import:
  "y.rkt" as pkernel:
    expose #{x.y}
```

where `y.rkt` has:

```
#lang racket/base
(provide x.y)
(define x.y 1)
```

produces the error:

```
Welcome to DrRacket, version 8.11.1.7 [cs].
Language: rhombus/static/and_meta, with debugging; memory limit: 256 MB.
. import: identifier to expose is not provided in: #{x.y}
> 
```

**Comment by mflatt** [comment]
The relevant changes was 9c5ebbd1ea4ec7f23bc2013eb91a6c9948931384. I knew that `.` in imported Racket identifiers would be an issue, but I didn't expect it to be an issue right away. I'm not immediately certain of the repair, but I think it can be fixed.

**Comment by rfindler** [comment]
I can change the identifier! No problem!

Robby

**Comment by usaoc** [comment]
Can we keep this open to track the issue?

**Comment by rfindler** [comment]
Oh, sure, I've reopened it. (I also changed the [offending](https://github.com/rfindler/esterel/commit/8efcbdc33bf31317bd2a6cf338d8939ce7aadb54) [code](https://github.com/rfindler/esterel/commit/8b3b659971640cae5d70d2f51a1a7a08c3f860e0) so it isn't a problem for me currently.)
