### ISSUE TITLE
`values` reducer incorerctly propagates initial-value static info

### ISSUE THREAD

**Issue by mflatt** [racket/rhombus-prototype#449]
The following example is currently allowed statically:

```
#lang rhombus/static

class Posn(x, y)

for values(p = Posn(1, 2)) (i: 0..2):
  p.x
```

The problem is that the `values` reducer incorrectly transfers static info from `Posn(1, 2)` to the binding `p`. I introduced this bug in eeb362d4, likely in an attempt to make the loop in `gui_demo.rhm` nicer. Unfortunately, other Rhombus code likely relies on this incorrect inference.

A possible change is allow a binding form on the left-hand side of `=`, instead of allowing only an identifier, and then you can at least write `values(p :: Posn = Posn(1, 2)`. That would be more similar to `recur`. I don't have an idea that would allow a `:: Posn` to be omitted.

**Comment by usaoc** [comment]
This is also a good place to add support for blocks in place of simple expressions, as in `fun` and `recur`.

**Comment by usaoc** [comment]
Allowing arbitrary binding forms seems more difficult to fit into existing `for` protocols (maybe I’m missing something here).  For example, I’m not sure where to put the `definer`s to achieve a reasonable scope.  Limited support for annotations is a more realistic goal.

**Comment by mflatt** [comment]
Ah, right. I think that's why I didn't implement it that way in the first place. Maybe we can only support annotations on the accumulators, similar to the fields of `class`.
