### ISSUE TITLE
arity error in annot.macro implementation

### ISSUE THREAD

**Issue by rfindler** [racket/rhombus-prototype#468]
This program:

```
#lang rhombus/and_meta

annot.macro '$d -> $r':
  'converting(fun (x): x)'
  
def h :: Int -> Boolean:
  1
```

produces the error 

```
...ate/annot-macro.rkt:86:3: wrong number of arguments in function call
  expected: 2
  given: 3
```

probably because a protocol somewhere changed and `annot.macro` didn't get updated. Specifically, it looks like [this function](https://github.com/racket/rhombus-prototype/blob/master/rhombus/private/annot-macro.rkt#L86) should actually have three arguments.

**Comment by usaoc** [comment]
What’s happening is that it’s missing handling of the `automatic` protocol, which passes three arguments instead of two.  The `automatic` protocol is used here because the pattern required a parsed right-hand side.

**Comment by rfindler** [comment]
Thanks!
